import { StyleSheet } from 'react-native';

import { theme } from '../constants/theme';

const { actions, borders, effects, overlays, progress: progressTheme, surfaces, text } = theme;

export const appStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: surfaces.surface1,
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  screenContainer: {
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 24,
    gap: 20,
  },
  heroBlock: {
    gap: 8,
  },
  eyebrow: {
    color: actions.primaryBg,
    fontSize: 13,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  heroTitle: {
    color: text.primary,
    fontSize: 34,
    fontWeight: '800',
    textAlign: 'center',
  },
  heroSubtitle: {
    color: text.muted,
    fontSize: 16,
    lineHeight: 22,
  },
  card: {
    flex: 1,
    backgroundColor: surfaces.surface2,
    borderRadius: 24,
    padding: 18,
    shadowColor: effects.shadowColor,
    shadowOpacity: 0.08,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  setupFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
  },
  setupNavButton: {
    width: 52,
    height: 52,
    borderRadius: 18,
  },
  stepDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
  },
  stepDot: {
    width: 10,
    height: 10,
    borderRadius: 999,
    backgroundColor: borders.strong,
  },
  stepDotActive: {
    width: 28,
    backgroundColor: actions.primaryBg,
  },
  stepBody: {
    flex: 1,
  },
  stepSection: {
    flex: 1,
    gap: 12,
  },
  stepSectionCentered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
  },
  sectionTitle: {
    color: text.primary,
    fontSize: 24,
    fontWeight: '800',
    textAlign: 'center',
  },
  sectionHint: {
    color: text.secondary,
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  sectionHintCentered: {
    color: text.secondary,
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  rowGap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  addIconButton: {
    width: 52,
    height: 52,
    borderRadius: 16,
  },
  textInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: borders.subtle,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    color: text.input,
    backgroundColor: surfaces.surfaceInput,
    fontSize: 16,
  },
  list: {
    flex: 1,
  },
  listContent: {
    gap: 10,
    paddingBottom: 8,
  },
  playerListContent: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
  },
  inlineEditorRow: {
    backgroundColor: surfaces.surfaceInset,
    borderRadius: 16,
    padding: 8,
  },
  playerInlineEditorRow: {
    width: '100%',
  },
  inlineInput: {
    borderWidth: 1,
    borderColor: borders.subtle,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: text.input,
    fontSize: 16,
    backgroundColor: surfaces.surface2,
  },
  pillRow: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: borders.subtle,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 10,
    maxWidth: '100%',
    backgroundColor: surfaces.surface2,
  },
  pillLabelWrap: {
    flexShrink: 1,
  },
  pillLabel: {
    color: text.input,
    fontSize: 16,
    fontWeight: '700',
  },
  pillDelete: {
    borderWidth: 1,
    borderColor: borders.muted,
    borderRadius: 999,
    backgroundColor: surfaces.surface1,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  countText: {
    color: actions.primaryText,
    fontSize: 44,
    fontWeight: '800',
  },
  counterActions: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 12,
  },
  groupsChooserWrap: {
    marginTop: 'auto',
  },
  segmentRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'center',
    marginTop: 8,
  },
  segment: {
    borderWidth: 1,
    borderColor: borders.subtle,
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: surfaces.surface2,
  },
  segmentActive: {
    backgroundColor: actions.primaryBg,
    borderColor: actions.primaryBg,
  },
  segmentLabel: {
    color: text.primary,
    fontSize: 14,
    fontWeight: '700',
  },
  segmentLabelActive: {
    color: actions.primaryText,
  },
  teamNameChip: {
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  teamNameChipText: {
    fontSize: 18,
    fontWeight: '700',
    textTransform: 'capitalize',
  },
  scoreInput: {
    minWidth: 160,
    textAlign: 'center',
    borderWidth: 1,
    borderColor: borders.subtle,
    borderRadius: 18,
    paddingHorizontal: 20,
    paddingVertical: 16,
    color: text.primary,
    fontSize: 28,
    fontWeight: '700',
    backgroundColor: surfaces.surface2,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: overlays.scrim,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  modalCard: {
    width: '100%',
    backgroundColor: surfaces.surface2,
    borderRadius: 24,
    padding: 20,
    gap: 18,
  },
  modalTitle: {
    color: text.primary,
    fontSize: 22,
    fontWeight: '800',
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
  },
  splitContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  splitCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: surfaces.surface2,
    borderRadius: 28,
    padding: 24,
    gap: 20,
    shadowColor: effects.shadowColor,
    shadowOpacity: 0.08,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  splitName: {
    textAlign: 'center',
    fontSize: 38,
    fontWeight: '800',
    textTransform: 'capitalize',
  },
  gameScroll: {
    flex: 1,
  },
  gameContent: {
    padding: 20,
    gap: 16,
  },
  gameHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  gameTitle: {
    color: text.primary,
    fontSize: 30,
    fontWeight: '800',
  },
  gameHeaderButton: {
    minHeight: 40,
    paddingHorizontal: 14,
    borderRadius: 12,
  },
  gameHeaderButtonText: {
    color: actions.secondaryText,
    fontSize: 14,
    fontWeight: '800',
  },
  teamCard: {
    backgroundColor: surfaces.surface2,
    borderRadius: 24,
    overflow: 'hidden',
    shadowColor: effects.shadowColor,
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  teamHeader: {
    borderLeftWidth: 6,
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: surfaces.surfaceHeader,
  },
  teamTitle: {
    fontSize: 24,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  teamPlayers: {
    paddingHorizontal: 16,
    paddingTop: 12,
    gap: 10,
  },
  teamMateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 4,
  },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    fontSize: 16,
    fontWeight: '800',
  },
  teamMateName: {
    color: text.input,
    fontSize: 16,
    fontWeight: '600',
  },
  scoreCard: {
    padding: 16,
    gap: 16,
  },
  scoreTitle: {
    textAlign: 'center',
    fontSize: 24,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  scoreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
  },
  scoreButton: {
    width: 54,
    height: 54,
    borderRadius: 16,
  },
  scoreButtonText: {
    color: actions.primaryText,
    fontSize: 28,
    fontWeight: '800',
  },
  scoreValue: {
    minWidth: 96,
    textAlign: 'center',
    fontSize: 32,
    fontWeight: '800',
  },
  scoreControllers: {
    flexDirection: 'row',
    gap: 12,
  },
  pointInputWrap: {
    flex: 1,
    gap: 8,
  },
  pointLabel: {
    fontSize: 14,
    fontWeight: '700',
  },
  pointInput: {
    borderWidth: 1,
    borderColor: borders.subtle,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: text.input,
    backgroundColor: surfaces.surface2,
  },
  progressWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  progressTrack: {
    flex: 1,
    height: 18,
    borderRadius: 999,
    backgroundColor: progressTheme.track,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
  },
  progressLabel: {
    minWidth: 44,
    color: text.secondary,
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'right',
  },
  emptyState: {
    borderRadius: 16,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: borders.subtle,
    padding: 18,
    backgroundColor: surfaces.surfaceInput,
  },
  emptyStateCompact: {
    paddingVertical: 12,
  },
  emptyStateText: {
    color: text.secondary,
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  button: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonTextFrame: {
    minHeight: 52,
    paddingHorizontal: 18,
    borderRadius: 16,
  },
  buttonGrow: {
    flex: 1,
  },
  buttonPrimary: {
    backgroundColor: actions.primaryBg,
  },
  buttonSecondary: {
    backgroundColor: actions.secondaryBg,
    borderWidth: 2,
    borderColor: borders.subtle,
  },
  buttonPrimaryDisabled: {
    backgroundColor: actions.disabledPrimaryBg,
  },
  buttonSecondaryDisabled: {
    backgroundColor: actions.disabledSecondaryBg,
    borderColor: borders.subtle,
  },
  buttonPressed: {
    opacity: actions.pressedOpacity,
  },
  buttonText: {
    fontSize: 16,
    fontWeight: '800',
  },
  buttonPrimaryText: {
    color: actions.primaryText,
  },
  buttonPrimaryTextDisabled: {
    color: actions.disabledPrimaryText,
  },
  buttonSecondaryText: {
    color: actions.secondaryText,
  },
  buttonSecondaryTextDisabled: {
    color: actions.disabledSecondaryText,
  },
});
